---
:concurrency: 2
:queues:
  - jokou_development_default
  - jokou_development_mailers

:schedule:
  banner:
    cron: '0 0 0 * * * Africa/Abidjan'   
    class: BannerJob
    enable: true
  
  bid_active:
    cron: '* * * * * Africa/Abidjan'
    class: SetBidStateJob
    every: "30m"
    enable: true