---
:concurrency: 2
:queues:
  - jokou_default
  - jokou_mailers

:schedule:
  banner:
    cron: '0 * * * * * Africa/Abidjan'   
    class: BannerJob
    every: "30m" # Set 30 min
    enable: true
  
  bid_active:
    cron: '0 * * * * * Africa/Abidjan'
    class: SetBidStateJob
    every: "30m" # Set 30 min
    enable: true