---
:concurrency: 2
:queues:
  - jokou_default
  - jokou_mailers

:schedule:
  banner:
    # cron: '0 0 * * * * Africa/Abidjan'   
    class: BannerJob
    every: '24h'
    enable: true
  
  bid_active:
    cron: '*/30 * * * * Africa/Abidjan'
    class: SetBidStateJob
    enable: true